name: samplehitch
description: hitch_prototype_self


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  animated_text_kit: ^2.1.0
  google_fonts: ^0.3.8
  font_awesome_flutter: '>= 4.7.0'
  keyboard_avoider: ^0.1.2
  flat_icons_flutter: ^1.0.2
  flutter_fluid_slider: ^1.0.2



dev_dependencies:

  flutter_test:
    sdk: flutter



flutter:
  assets:
    - assets/
  uses-material-design: true
  fonts:
    - family: Spartan
      fonts:
        - asset: fonts/Spartan/Spartan-Regular.ttf
    - family: Sanchez
      fonts:
        - asset: fonts/Sanchez/Sanchez-Regular.ttf
